# Generated by Django 3.0.2 on 2022-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('surname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=122)),
                ('message', models.TextField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
